name: NPM Publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.3.18)'
        required: true
        type: string

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        continue-on-error: true
        
      - name: Run type checking
        run: npm run type-check
        
      - name: Run tests
        run: npm test
        
      - name: Build project
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la dist/
          if [ ! -f dist/index.js ]; then
            echo "Error: dist/index.js not found"
            exit 1
          fi
          if [ ! -f dist/index.js.map ]; then
            echo "Error: dist/index.js.map not found"
            exit 1
          fi
          echo "Build output verified ✓"
          
      - name: Generate build checksums
        run: |
          echo "Generating SHA256 checksums..."
          sha256sum dist/* > dist/checksums.sha256
          cat dist/checksums.sha256
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json
            package-lock.json
            README.md
            LICENSE
            CHANGELOG.md
            bin/
            
  publish:
    name: Publish to NPM
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: npm-production
    
    permissions:
      contents: write
      id-token: write  # Required for npm provenance
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          
      - name: Install dependencies
        run: npm ci
        
      - name: Verify package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            TAG_VERSION="${{ github.event.inputs.version }}"
          fi
          
          echo "Package version: $PACKAGE_VERSION"
          echo "Tag version: $TAG_VERSION"
          
          if [ "$PACKAGE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Package version ($PACKAGE_VERSION) doesn't match tag version ($TAG_VERSION)"
            exit 1
          fi
          
      - name: Create npm package tarball
        run: npm pack --dry-run
        
      - name: Publish to NPM with provenance
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Extract version from tag or input
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
          
      - name: Extract release notes from CHANGELOG
        id: extract_notes
        run: |
          VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Extracting notes for version $VERSION..."
          
          # Extract the section for this version from CHANGELOG.md
          NOTES=$(awk "/^## \[$VERSION\]/{flag=1; next} /^## \[/{flag=0} flag" CHANGELOG.md)
          
          if [ -z "$NOTES" ]; then
            echo "No release notes found for version $VERSION in CHANGELOG.md"
            NOTES="See [CHANGELOG.md](https://github.com/vibe-log/vibe-log-cli/blob/main/CHANGELOG.md) for details."
          fi
          
          # Save to file to handle multiline content
          echo "$NOTES" > release_notes.txt
          echo "Release notes extracted successfully"
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body_path: release_notes.txt
          files: |
            dist/checksums.sha256
          append_body: true
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
